name: horse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Verify Node.js Installation
      run: node --version
    - name: Setup Newman
      run: npm install -g newman
    - name: Verify Newman Installation
      run: newman --version
    - name: Launch Console Application
      run: start ./Console.exe
    - name: Running Postman Tests Console Application
      run: newman run ./Postman/rest-api-delphi-horse.postman_collection.json --environment ./Postman/horse-console-application.postman_environment.json --insecure
    - name: Launch VCL Application
      run: start ./VCL.exe
    - name: Running Postman Tests VCL Application
      run: newman run ./Postman/rest-api-delphi-horse.postman_collection.json --environment ./Postman/horse-application.postman_environment.json --insecure
    - name: Launch DUnitX
      run: ./DUnitX.exe
